// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDbZNsBz7cpyh5h7iPAZH3YuI0SScL80g',
    appId: '1:605450405329:web:6e139934134189d3c34cf0',
    messagingSenderId: '605450405329',
    projectId: 'heart-care-firebase-d19a0',
    authDomain: 'heart-care-firebase-d19a0.firebaseapp.com',
    storageBucket: 'heart-care-firebase-d19a0.firebasestorage.app',
    measurementId: 'G-RQ13D76W70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23qOmcxgfTjJSxrVd99OdGDZjBdcZNaY',
    appId: '1:605450405329:android:40d69ecab4f2296ac34cf0',
    messagingSenderId: '605450405329',
    projectId: 'heart-care-firebase-d19a0',
    storageBucket: 'heart-care-firebase-d19a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVeHpk_PWReddx5iLOBPP7A9EfsgemnTI',
    appId: '1:605450405329:ios:d30467f2435f00abc34cf0',
    messagingSenderId: '605450405329',
    projectId: 'heart-care-firebase-d19a0',
    storageBucket: 'heart-care-firebase-d19a0.firebasestorage.app',
    iosBundleId: 'com.example.heartcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVeHpk_PWReddx5iLOBPP7A9EfsgemnTI',
    appId: '1:605450405329:ios:d30467f2435f00abc34cf0',
    messagingSenderId: '605450405329',
    projectId: 'heart-care-firebase-d19a0',
    storageBucket: 'heart-care-firebase-d19a0.firebasestorage.app',
    iosBundleId: 'com.example.heartcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDbZNsBz7cpyh5h7iPAZH3YuI0SScL80g',
    appId: '1:605450405329:web:e170cf1481d9751ec34cf0',
    messagingSenderId: '605450405329',
    projectId: 'heart-care-firebase-d19a0',
    authDomain: 'heart-care-firebase-d19a0.firebaseapp.com',
    storageBucket: 'heart-care-firebase-d19a0.firebasestorage.app',
    measurementId: 'G-S8Q1HR9PK8',
  );
}
